
import os
import sys
from dotenv import load_dotenv
load_dotenv()
PROJECT = os.getenv('PROJECT')
DATASET = os.getenv('DATASET')
sql_text = f"""WITH
  C1 AS (
  SELECT
    FECHA_VALORACION,
    AVG(PRECIO_VALORACION) OVER (PARTITION BY NEMOTECNICO,FECHA_VALORACION) AS PRECIO,
    LAG(AVG(PRECIO_VALORACION)) OVER (PARTITION BY NEMOTECNICO ORDER BY FECHA_VALORACION) AS ANTERIOR,
    LAG(FECHA_VALORACION) OVER (PARTITION BY NEMOTECNICO ORDER BY FECHA_VALORACION) AS FECHA_ANTERIOR,
    NEMOTECNICO,
    CODIGO_FONDO,
    CODIGO_PORTAFOLIO,
    CUSIP,
    CLASE_INVERSION,
  FROM
    `sura-inception.proteccion_co_zcarga_inversiones.SQLSERVER_SPIRITDB_SPIRIT_TSPT_VALORACION_POS`
  WHERE
    PRECIO_VALORACION !=0
    AND NEMOTECNICO IS NOT NULL
    AND NEMOTECNICO != ''
  GROUP BY
    FECHA_VALORACION,
    PRECIO_VALORACION,
    NEMOTECNICO,
    CODIGO_FONDO,
    CODIGO_PORTAFOLIO,
    CUSIP,
    CLASE_INVERSION
  ORDER BY
    NEMOTECNICO,
    FECHA_VALORACION DESC),
  C2 AS (
  SELECT
    FECHA_VALORACION,
    FECHA_ANTERIOR,
    PRECIO,
    MAX(FECHA_VALORACION) OVER (PARTITION BY NEMOTECNICO ORDER BY NEMOTECNICO) AS MAX_DATE,
    ANTERIOR,
    (PRECIO-ANTERIOR)/ANTERIOR AS CAMBIO,
    NEMOTECNICO,
    CODIGO_FONDO,
    CODIGO_PORTAFOLIO,
    CUSIP,
    CLASE_INVERSION
  FROM
    C1
  GROUP BY
  FECHA_VALORACION,FECHA_ANTERIOR,PRECIO,ANTERIOR,NEMOTECNICO,CODIGO_FONDO,CODIGO_PORTAFOLIO,CUSIP,CLASE_INVERSION
  ORDER BY
    NEMOTECNICO,
    FECHA_VALORACION)
SELECT
  C2.FECHA_VALORACION,
  C2.FECHA_ANTERIOR,
  C2.MAX_DATE,
  C2.CLASE_INVERSION,
  AVG(V.VALOR_INTERESES) AS INTERESES, #dividendos 
  AVG(V.VALOR_NOMINAL_OP) AS VALOR_NOMINAL_OP,
  C2.PRECIO,
  C2.ANTERIOR,
  C2.CAMBIO,
  C2. NEMOTECNICO,
FROM
  C2
LEFT JOIN `sura-inception.proteccion_co_zcarga_inversiones.SQLSERVER_SPIRITDB_SPIRIT_TSPT_VENCIMIENTOS` AS V ON C2.FECHA_VALORACION = V.FECHA
AND C2.CODIGO_FONDO = V.CODIGO_FONDO
AND C2.CODIGO_PORTAFOLIO = V.CODIGO_PORTAFOLIO
AND C2.CUSIP = V.CUSIP
AND C2.CLASE_INVERSION = V.CLASE_INVERSION
WHERE C2.FECHA_VALORACION != C2.FECHA_ANTERIOR
GROUP BY
C2.FECHA_VALORACION,
C2.FECHA_ANTERIOR,
C2.PRECIO,
C2.ANTERIOR,
C2.CAMBIO,
MAX_DATE,
C2.CLASE_INVERSION,
V.VALOR_INTERESES, #dividendos 
V.VALOR_NOMINAL_OP,
C2.NEMOTECNICO
ORDER BY
  NEMOTECNICO,
  FECHA_VALORACION"""